name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7

      - uses: xyzzylabs/setup-zig@v1
        with:
          version: master

      - run: zig build install test --summary all
